TITLE: thermcampos blog
TITLE_HTML: thermcampos
TAGLINE: Welcome to my blog, personal corner and stuff
#POSTS_PER_PAGE: 10
AUTHOR: R. Campos
COMMENTS: isso
ISSO_URL: https://comments.thermcampos.blog/
#DISQUS: your-disqus-id
TIMEZONE: UTC
#POST_EXT: .rst
THEME: Dark
TRANSLATE: False
EXTENSIONS:
  - sidebar
