TITLE: RMCampos Blohg
TITLE_HTML: RMCampos blog
TAGLINE: Welcome to my personal corner and stuff
#POSTS_PER_PAGE: 10
AUTHOR: Ricardo Campos
#DISQUS: your-disqus-id
TIMEZONE: UTC
#POST_EXT: .rst
THEME: Dark
